[phases.setup]
nixPkgs = ["nodejs_22", "rustc", "cargo", "gcc", "pkg-config", "openssl"]

[phases.install]
cmds = [
  "npm install",
  "rustup default stable",
  "rustup target add wasm32-unknown-unknown",
  "cargo install --locked --version 4.1.1 cargo-contract"
]

[start]
cmd = "npm start"
